# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: '7c37eeeb-3ccc-419c-adad-c4b001b3f1a4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'itrnityTrainer-rg'
    location: 'Central India'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/nivedv/ARMPipeline-repo/refs/heads/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName nvprjtemp'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
